"""
list of movies to choose randomly to play game
"""

movies_list = [
    "Harry Potter",
    "The Lord of the Rings",
    "Back to the Future",
    "The Godfather",
    "Forrest Gump",
    "Parasite",
    "Inception",
    "The Dark Knight",
    "Good Will Hunting",
    "Fight Club",
    "Pulp Fiction",
    "The Shawshank Redemption",
    "Titanic",
    "The Green Mile",
    "The Princess Bride",
    "A Space Odyssey",
    "Citizen Kane",
    "Angry Men",
    "The Matrix",
    "Seven",
    "The Silence of the Lambs",
    "City of God",
    "Goodfellas",
    "Saving Private Ryan",
    "Life is Beautiful",
    "Star Wars",
    "Psycho",
    "The Pianist",
    "Parasite",
    "Gladiator",
    "The Departed",
    "The Usual Suspects",
    "Braveheart",
    "Toy Story",
    "Die Hard",
    "The Sixth Sense",
    "A Beautiful Mind",
    "Shutter Island",
    "Jurassic Park",
    "Finding Nemo",
    "Gone with the Wind",
    "Mary Poppins",
    "The Terminator",
    "The Wizard of Oz",
    "Groundhog Day",
    "The Incredibles",
    "Pirates of the Caribbean",
    "The Sound of Music",
    "Brokeback Mountain",
    "Black Panther",
    "La La Land",
    "The Social Network",
    "Saving Private Ryan",
    "Cast Away",
    "Ghostbusters",
    "The Shining",
    "Little Women",
    "When Harry Met Sally",
    "City of Angels",
    "Sleepless in Seatle",
    "The Women",
    "Top Gun",
    "The Terminal",
    "Catch Me If You Can",
    "Philadelphia",
    "My Big Fat Greek Wedding",
    "Mrs Doubtfire",
    "Jumanji",
    "Patch Adams",
    "Nine Months",
    "Pretty Woman",
    "Notting Hill",
    "Eat Pray Love",
    "Erin Brockovich",
    "Stepmom",
    "Knight and Day",
    "The Holiday",
    "Shrek",
    "Vanilla Sky",
    "Taken",
    "legally Blonde",
    "Vanity Fair",
    "Downton Abbey",
    "Sense and Sensibility",
    "Pride and Prejudice",
    "Wuthering Heights",
    "The Duchess",
    "Atonement",
    "The English Patient",
    "The Devil Wears Prada",
    "The Intern",
    "The Witches",
    "The Princess Diaries",
    "Bride Wars",
    "Just Go With It",
    "Along Came Polly",
    "The Pursuit of Happyness",
    "I Am Legend",
    "Independence Day",
    "Men in Black"
]